/* eslint-disable */
/* Generated by client-web/scripts/build_pwa.mjs. Do not edit by hand. */

const BUILD_ID = "0.1.69-5bb8119c95d1";
const CACHE_PREFIX = "yagodka-web-cache-";
const CACHE = CACHE_PREFIX + BUILD_ID;
const PRECACHE_URLS = [
  "./assets/index-Ci7EADok.js",
  "./assets/index-D-tWQSsp.css",
  "./boot.js",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/icon.svg",
  "./index.html",
  "./ios-input-bar-test.html",
  "./labs/ios-input-assistant.html",
  "./manifest.webmanifest",
  "./repro/ios-input-assistant.html",
  "./skins/amber.css",
  "./skins/cyberberry-crt.css",
  "./skins/default.css",
  "./skins/green.css",
  "./skins/showcase.css",
  "./skins/skins.json",
  "./skins/telegram-web.css"
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);
      await cache.addAll(PRECACHE_URLS);
    })()
  );
  // Do NOT call skipWaiting() automatically: обновление применяем только по подтверждению пользователя.
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      try {
        const keys = await caches.keys();
        await Promise.all(
          keys
            .filter((k) => k.startsWith(CACHE_PREFIX) && k !== CACHE)
            .map((k) => caches.delete(k))
        );
      } catch {}
      await self.clients.claim();
    })()
  );
});

self.addEventListener("message", (event) => {
  const data = event && event.data ? event.data : null;
  if (!data || typeof data !== "object") return;
  if (data.type === "SKIP_WAITING") {
    self.skipWaiting();
    return;
  }
  if (data.type === "GET_BUILD_ID") {
    const payload = { type: "BUILD_ID", buildId: BUILD_ID };
    try {
      if (event && event.source && typeof event.source.postMessage === "function") {
        event.source.postMessage(payload);
        return;
      }
      if (event && event.ports && event.ports[0] && typeof event.ports[0].postMessage === "function") {
        event.ports[0].postMessage(payload);
        return;
      }
    } catch {}
    self.clients
      .matchAll({ type: "window", includeUncontrolled: true })
      .then((clients) => clients.forEach((c) => c.postMessage(payload)))
      .catch(() => {});
  }
});

function isNavigationRequest(req) {
  return req.mode === "navigate" || req.destination === "document";
}

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (!req || req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // App shell: отдаём index.html из кэша, чтобы не смешивать версии index+assets.
  if (isNavigationRequest(req)) {
    event.respondWith(
      (async () => {
        const cache = await caches.open(CACHE);
        const cachedIndex = await cache.match("./index.html");
        if (cachedIndex) return cachedIndex;
        return fetch(req);
      })()
    );
    return;
  }

  event.respondWith(
    (async () => {
      const cache = await caches.open(CACHE);
      const cached = await cache.match(req);
      if (cached) return cached;
      const res = await fetch(req);
      if (res && res.ok) {
        cache.put(req, res.clone()).catch(() => {});
      }
      return res;
    })()
  );
});
